config/routes.rb
Rails.application.routes.draw do

  root                       'landing_pages#home'
  get     'about'         => 'landing_pages#about'
  get     'contact'       => 'landing_pages#contact'
  get     'help'          => 'landing_pages#help'

  get     'signup'        => 'workshops#new'
  get     'all_workshops' => 'workshops#index'
# get     'edit_workshop' => 'workshops#edit'

  get     'login'         => 'sessions#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'

  get     'new_reserv'    => 'reservations#new'

  get     'statistic'     => 'reports#statistic'
  get     'appointment'   => 'reports#appointment'
  resources :workshops
  resources :reservations
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
    if logged_in?
      @r_data = current_workshop.reservations.unscoped.
                where(workshop_id: current_workshop.id, date: Date.today).order(:time)
      @reservation = @r_data.paginate(:per_page => 10, :page => params[:page])
    end
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/landing_pages/_appointment_table.html.erb
<%= table_for @reservation,
  # Specifies the html classes to be applied to the table element
  :table_html => { :class => "table table-hover table-bordered" },

  # Specifies the namespace for generating links using Rails routing
  :link_namespace => :admin,

  # Specifies the classes and ids to be applied to each data row
  :data_row_html => {
    # The class of each row will alternate between four Twitter bootstrap classes: "success", "error", "warning", "info"
    :class => lambda { cycle('success', 'error', 'warning', 'info')},
    # Specifies the id using a Proc for each data row as "user-ID_OF_USER_RECORD"
    :id => lambda { |reservation| "user-#{reservation.id}" }
  } do |table| %>

  <% table.column :id, :header => "Reservation ID" %>
  <% table.column :name, :header => "Customer Name" %>
  <% table.column :car_model %>
  <% table.column :car_reg_number, :header => "Car Registration Number" %>
  <% table.column :service_type %>
  <% table.column :time, :formatter => [:strftime, "%I:%M %p"] %>
  <% table.column :data => "Show", :link_url => lambda { |reservation| reservation_path(reservation.id) },
      :header => "Action" %>

  <%# Adds a footer that spans all the columns of the table and shows pagination links for the table %>
  <% table.footer do %>
    <div class="pull-right">
      <%= will_paginate @reservation %>
    </div>
  <% end %>

<% end %>

app/views/landing_pages/_dashboard.html.erb
<div class="jumbotron workshop-header">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- The Header name, which is workshop name -->
      <div class="navbar-header">
        <a class="navbar-brand">Good day, <%= current_workshop.name %>!</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Place Reservation", new_reserv_path %></li>
          <li><%= link_to "Appointment", 'appointment' %></li>
          <li><%= link_to "All Reservations", reservations_path %></li>
          <li><%= link_to "Statistics", 'statistic' %></li>
        </ul>
      </div>
    </div>
  </nav>

  <hr>

  <div class="panel panel-body header-small-sec">
    <% if @reservation.count != 0 %>
      <h2>Today's Reservation</h2>
      <div class="panel panel-body">
        <%= render 'landing_pages/appointment_table' %>
      </div>
    <% elsif %>
      <h2>No reservation found, feel free to <%= link_to "place one", new_reserv_path %>.</h2>
    <% end %>
  </div>

  <!-- Pop Out Box-->
  <div id="popup-box" class="overlay">
    <div class="popup">
      <h2>New Reservation</h2>
      <a class="close" href="#">×</a>
      <div class="content">

      </div>
    </div>
  </div>

</div>

app/views/landing_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<div class="jumbotron">
	<p>
	  CarServIt is an online reservation application that helps you to keep track off your workshop reservation.
	</p>
</div>

app/views/landing_pages/contact.html.erb
<% provide(:title, "Contact Us") %>
<h1>Contact Us</h1>

<div class="jumbotron">
	
	<p>Contact Us @ </p>
	<br>

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Fadil</h3>
	  </div>

	  <div class="panel-body">
	    Contact: 018-2060472
	  </div>
	  <div class="panel-body">
	    Email: fadil.parves@gmail.com
	  </div>
	</div>

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Mac</h3>
	  </div>

	  <div class="panel-body">
	    Contact: 016-5579595
	  </div>
	  <div class="panel-body">
	    Email: yxshu94@gmail.com
	  </div>
	</div>

	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Uzair</h3>
	  </div>

	  <div class="panel-body">
	    Contact: 019-3656024
	  </div>
	  <div class="panel-body">
	    Email: mr.shezel@gmail.com
	  </div>
	</div>
</div>

app/views/landing_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<div class="jumbotron">

  <div class="panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading">Frequently asked questions (FAQs):</div>
    <div class="panel-body">
      Have questions? No Problem, browse through our FAQs :) <br><br>
    </div>

  <!-- List group -->
    <ul class="list-group">
      <li class="list-group-item">1. What is CarServIt?</li>
      <li class="list-group-item">CarServIt is an online reservation application that designed for car workshop to manage reservation. <br><br><br></li>

      <li class="list-group-item">2. Is there there any charges to use CarServIt?</li>
      <li class="list-group-item">Nope, CarServIt is free to use. <br><br><br></li>

      <li class="list-group-item">3. How do I change my password? </li>
      <li class="list-group-item">In settings. <br><br><br></li>
    </ul>
  </div>
</div>

app/views/landing_pages/home.html.erb
    <!-- Workshop Logged In Menu -->
    <% if logged_in? %>
      <%= render 'landing_pages/dashboard' %>

    <!-- Home page Menu (User not logged In) -->
    <% else %>
      <div class="center panel col-md-12 main_header">
        <br><h1>CarServIt</h1><br>
        <p>YOUR WORKSHOP SERVICING E-MANAGER</p>
        <hr>

        <div class="row">
          <br><br>
            <!-- Services Section -->
            <div class="center col-md-3">
              <div class="my-inner panel panel-body section-sizing service-prop">
                <br><br>
                <%= image_tag("user.png", alt: "CarServIt logo", :size => "100x100")%>
                <br><br>
                <h4>All-in-one workshop management assistant.</h4>
              </div>
            </div>

            <!-- User Friendly Section -->
            <div class="center col-md-3 ">
              <div class="my-inner panel panel-body section-sizing dashboard-panel user-friendly-prop">
                <br><br>
                <%= image_tag("cloud.png", alt: "User friendly", :size => "100x100")%>
                <br><br>
                <h4>Store your reservations on the cloud.</h4>
              </div>
            </div>

            <!-- Computerized Section -->
            <div class="center col-md-3 ">
              <div class="my-inner panel panel-body section-sizing dashboard-panel computerized-prop">
                <br><br>
                <%= image_tag("maintainance.png", :size => "100x100")%>
                <br><br>
                <h4>Worries-free management and maintainance.</h4>
              </div>
            </div>

            <!-- Notification Section -->
            <div class="center col-md-3 ">
              <div class="my-inner panel panel-body section-sizing dashboard-panel notification-prop">
                <br><br>
                <%= image_tag("sms.png", alt: "SMS", :size => "100x100")%>
                <br><br>
                <h4>Automated notification to your customer.</h4>
              </div>
            </div>
        </div>
        <br>
      </div>

      <div class="row">
        <br><br><br>
      </div>

      <!-- Subscribtion Section -->
      <div class="panel panel-body center subscribe-prop">
        <%= image_tag("email.png", :size => "200x200")%>
        <h1 class="section-heading">Subscribe</h2>
        <h3>Subscribe to get more updates about CarServIt!</h3>
        <br>
        <div class="row">
          <div class="col-lg-12">
            <form action="https://carservit.us11.list-manage.com/subscribe/post?u=d0208299ea8b17c26bc646288&amp;id=2dcfc1f698" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
                  <div class="form-group">
                    <input type="email" name="EMAIL" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <div id="success"></div>
                  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;"><input type="text" name="b_d0208299ea8b17c26bc646288_2dcfc1f698" tabindex="-1" value=""></div>
                  <br>
                  <%= link_to "Subscribe", '#', class: "btn btn-lg btn-primary" %>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
  <% end %>