config/routes.rb
Rails.application.routes.draw do

  root                       'landing_pages#home'
  get     'about'         => 'landing_pages#about'
  get     'contact'       => 'landing_pages#contact'
  get     'help'          => 'landing_pages#help'

  get     'signup'        => 'workshops#new'
  get     'all_workshops' => 'workshops#index'
# get     'edit_workshop' => 'workshops#edit'

  get     'login'         => 'sessions#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'

  get     'new_reserv'    => 'reservations#new'

  get     'statistic'     => 'reports#statistic'
  get     'appointment'   => 'reports#appointment'
  resources :workshops
  resources :reservations
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :workshop
	# Short the Reservation from latest to older
	default_scope -> { order(created_at: :desc) }
  validates :workshop_id, presence: true

	before_save :upcase_car_reg_number
	validates :name, 						presence: true, length: { maximum: 50 }
	validates :contact_number, 	presence: true, length: { maximum: 11 }
	validates :car_model, 			presence: true, length: { maximum: 15 }
	validates :car_reg_number, 	presence: true, length: { maximum: 10 }
	validates :service_type, 		presence: true
	validates :time, 						presence: true
	validates :date, 						presence: true
	validates :service_type, 		presence: true
	validates :time, 						presence: true
	validates :date, 						presence: true
	validate :present_date


	# It returns the Reservation
  def self.search(query)
    # where(:id, query) -> This would return an exact match of the query
    where("id like ?", "%#{query}%")
  end

	def present_date
    errors.add(:date, "can't be in the past") if
		!date.blank? and date < Date.today
  end

	private

	def upcase_car_reg_number
		self.car_reg_number = car_reg_number.upcase
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :logged_in_workshop, only: [:index, :show, :create, :destroy, :edit, :update]

	def new
		@reservation = current_workshop.reservations.build
	end

	def index
		if params[:search]
			@reservation = current_workshop.reservations.where(car_reg_number: params[:search])
		else
			@reservations = current_workshop.reservations.paginate(page: params[:page])
		end
	end

	def show
		@reservation = current_workshop.reservations.find(params[:id])
	end

	def create
     @reservation = current_workshop.reservations.build(reserve_params)
      if @reservation.save
      	@client = Twilio::REST::Client.new ENV["acc_SID"],
				ENV["auth_token"]
				@client.messages.create(
  				from: ENV["twi_from"],
  				to: ENV["twi_to"],
  				body: "Thank You for choosing us for your car maintainence. \n Here is the details for your reservation: \n ID: #{@reservation.id} \n Name: #{@reservation.name} \n Ph Number: #{@reservation.contact_number} \n Car Model: #{@reservation.car_model} \n Car Plate: #{@reservation.car_reg_number} \n Service Type: #{@reservation.service_type} \n Time: #{@reservation.time.strftime('%I:%M %P')} \n Date: #{@reservation.date} \n Enjoy more mileage with the new primax95 from Petronas. \n Have a good day!"
					)
				flash[:success] = "Reservation made."
				redirect_to @reservation
    	else
      	render 'new'
      end
    end

	def edit
		@reservation = current_workshop.reservations.find(params[:id])
	end

	def update
    @reservation = current_workshop.reservations.find(params[:id])
    	if @reservation.update_attributes(reserve_params)
			@client = Twilio::REST::Client.new ENV["acc_SID"],
			ENV["auth_token"]
			@client.messages.create(
				from: ENV["twi_from"],
				to: ENV["twi_to"],
				body: "Thank You for choosing us for your car maintainence.\n Here is the details for your reservation: \n ID: #{@reservation.id} \n Name: #{@reservation.name} \n Ph Number: #{@reservation.contact_number} \n Car Model: #{@reservation.car_model} \n Car Plate: #{@reservation.car_reg_number} \n Service Type: #{@reservation.service_type} \n Time: #{@reservation.time.strftime('%I:%M %P')} \n Date: #{@reservation.date} \n Enjoy more mileage with the new primax95 from Petronas. \n Have a good day!"
				)
      		flash[:success] = "Reservation updated"
			redirect_to @reservation
    	else
      		render 'edit'
    	end
  	end

  	def destroy
  		Reservation.find(params[:id]).destroy
  		flash[:success]= "Reservation deleted!"
  		redirect_to root_url
  	end

  private

    def reserve_params
      params.require(:reservation).permit(:name, :contact_number, :car_model,:car_reg_number, :service_type,
                                   				:time, :date)
    end

		def correct_workshop
			@reservation = current_workshop.microposts.find_by(id: params[:id])
			redirect_to root_url if @reservation.nil?
		end
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/_index.html.erb
<h4 class="center"><b>All Reservation</b></h4>

<%= form_tag(reservations_path, :method => "get", class: "navbar-form") do %>
  <div class="input-append center">
    <%= text_field_tag :search, params[:search.upcase], class: "span2", placeholder: "Search Reservation, Enter Car Registration Number" %>
    <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
      of using a Rails form helper -->
  <button class="btn btn-primary" type="submit"><b class="icon-search">Search</b></button>
</div>
<% end %>

<br>

<%= will_paginate %>
<!-- <ul class="reserved"> -->
    <table class="table">
      <tr>
        <td class="no-repeat-header">#</td>
        <td class="no-repeat-header">ID</td>
        <td class="no-repeat-header">Reg Number</td>
        <td class="no-repeat-header">Date</td>
        <td class="no-repeat-header">Time</td>
        <td class="no-repeat-header"> </td>
        <td class="no-repeat-header"> </td>
        <td class="no-repeat-header"> </td>
      </tr>
      <% @reservations.each_with_index do |reservation, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= "R"+"%05d" % reservation.id %></td>
        <td><%= reservation.car_reg_number %></td>
        <td><%= reservation.date %></td>
        <td><%= reservation.time.strftime('%I:%M %P') %></td>
        <td><%= link_to "View", reservation %></td>
        <td><%= link_to "Edit", edit_reservation_path(reservation) %></td>
        <td><% if current_workshop.admin? || current_workshop?(reservation.workshop) %>
           <%= link_to "Delete", reservation_path(reservation.id), method: :delete, data: { confirm: "You sure?"}%>
        <% end %><td>
      </tr>
      <% end %>
    </table>

<%= will_paginate %>

app/views/reservations/edit.html.erb
<% provide(:title, 'Edit Reservation') %>
<h1>Edit Reservation</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@reservation) do |f| %>
    <%= render 'shared/reservation_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :contact_number %>
      <%= f.number_field :contact_number, class: 'form-control' %>

      <%= f.label :car_model %>
      <%= f.text_field :car_model, class: 'form-control' %>

      <%= f.label :car_registration_number %>
      <%= f.text_field :car_reg_number, class: 'form-control' %>

      <%= f.label :service_type %>
      <%= f.select :service_type, options_for_select(["Minor Service", "Major Service", "Car Checkup"]), {}, { class: 'form-control' } %>

      <%= f.label :time %>
      <%= f.time_field :time, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>

      <%= f.submit "Confirm", class: "btn btn-primary" %>
      <br></br>
      <%= button_tag "Reset", type: :reset, class: "btn btn-danger btn-block" %>
      <br></br>
      <%= link_to "Back" , reservations_path , class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<% provide(:title, 'All reservation') %>

<%= render 'reservations/index' %>

<div class="center">
  <%= link_to "Back", root_path, class: "btn btn-primary" %>
</div>

app/views/reservations/new.html.erb
<% provide(:title, 'Reservation') %>
<h1>Reservation</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@reservation) do |f| %>
    <%= render 'shared/reservation_error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :contact_number %>
      <%= f.number_field :contact_number, class: 'form-control' %>

      <%= f.label :car_model %>
      <%= f.text_field :car_model, class: 'form-control' %>

      <%= f.label :car_registration_number %>
      <%= f.text_field :car_reg_number, class: 'form-control' %>

      <%= f.label :service_type %>
      <%= f.select :service_type, options_for_select(["Minor Service", "Major Service", "Car Checkup"]), {}, { class: 'form-control' } %>

      <%= f.label :time %>
      <%= f.time_field :time, class: 'form-control' %>

      <div class="form-group">
          <div class='input-group date' id='datetimepicker1' name='reservation[date]'>
              <input type='text' class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
          </div>
      </div>

      <%= f.submit "Confirm", class: "btn btn-primary" %>
      <br></br>
      <%= button_tag "Reset", type: :reset, class: "btn btn-danger btn-block" %>
      <br></br>
      <%= link_to "Back" , root_path , class: "btn btn-default btn-block" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
</script>

app/views/reservations/show.html.erb
<% provide(:title, 'Reservations') %>

<div class="jumbotron">
	<section class="user_info">

		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading"><h4>Reservation Details:</h4></div>
				<div class="panel-body center">
					<p>Your reservation details is shown as below, feel free to edit.</p>
				</div>

				<table class="table">
					<tr>
		        <td class="no-repeat-header"><b>ID</b></td>
		        <td class="no-repeat-header"><b>Name</b></td>
		        <td class="no-repeat-header"><b>Contact Number</b></td>
		        <td class="no-repeat-header"><b>Car Model</b></td>
		        <td class="no-repeat-header"><b>Car registration number</b></td>
						<td class="no-repeat-header"><b><b>Service type:</b></b></td>
						<td class="no-repeat-header"><b><b>Time:</b></b></td>
						<td class="no-repeat-header"><b><b>Date:</b></b></td>
					</tr>
					<tr>
						<td><%= @reservation.id %></td>
						<td><%= @reservation.name %></td>
						<td><%= @reservation.contact_number %></td>
						<td><%= @reservation.car_model %></td>
						<td><%= @reservation.car_reg_number %></td>
						<td><%= @reservation.service_type %></td>
						<td><%= @reservation.time.strftime('%I:%M %P') %></td>
						<td><%= @reservation.date %></td>
					</tr>

				</table>
				<hr>
				<br>
				<div class="center">
					<%= link_to "< Back", reservations_path, class: "panel-heading" %>
					<%= link_to "Edit Reservation", edit_reservation_path, class: "panel-heading" %>
					<% if current_workshop.admin? || current_workshop?(reservation.workshop) %>
	           <%= link_to "Delete", reservation_path(@reservation.id), class: "panel-heading",
						 			method: :delete, data: { confirm: "You sure?"}%>
	        <% end %>
				</div>
				<br>
			</div>
	</section>
</div>