config/routes.rb
Rails.application.routes.draw do

  root                       'landing_pages#home'
  get     'about'         => 'landing_pages#about'
  get     'contact'       => 'landing_pages#contact'
  get     'help'          => 'landing_pages#help'

  get     'signup'        => 'workshops#new'
  get     'all_workshops' => 'workshops#index'
# get     'edit_workshop' => 'workshops#edit'

  get     'login'         => 'sessions#new'
  post    'login'         => 'sessions#create'
  delete  'logout'        => 'sessions#destroy'

  get     'new_reserv'    => 'reservations#new'

  get     'statistic'     => 'reports#statistic'
  get     'appointment'   => 'reports#appointment'
  resources :workshops
  resources :reservations
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    CarServIt 2015. All right reserved.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <nav>
    <div class="container">
      <!-- The Header name, which is workshop name -->
      <div class="navbar-header">
        <%= link_to image_tag("logo.png", alt: "CarServIt logo", :size => "122x37"), root_path, id: "logo" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Dashboard",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
              <% if current_workshop.admin? %>
                <li><%= link_to "Workshops", all_workshops_path %></li>
              <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Profile", current_workshop %></li>
                <li><%= link_to "Settings", edit_workshop_path(current_workshop) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>

            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>

          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= render 'layouts/shim' %>
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67411529-1', 'auto');
  ga('send', 'pageview');

</script>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>